services:
  romarr-api:
    container_name: romarr-api-debug
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development