<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Romarr.Domain\Romarr.Domain.csproj" />
    <ProjectReference Include="..\..\src\Romarr.Application\Romarr.Application.csproj" />
    <ProjectReference Include="..\..\src\Romarr.Infrastructure\Romarr.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
  </ItemGroup>

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

</Project>
